// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hztwjgeayqjfpyrcwunj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6dHdqZ2VheXFqZnB5cmN3dW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjcyNDUsImV4cCI6MjA2NzU0MzI0NX0.CT8nWMMVdIUyprhYNizO2TpbOxHnpTt2kj60EWPl6zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});